let shopItemsData = [
    {
    id: "a",
    name: "Jeevaan - The Perfect Shirt",
    price: 499,
    desc: "Cotton Men's Regular Fit Formal Shirt",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh1.jpg",
    },
    {
    id: "b",
    name: "Men's sun suit",
    price: 1299,
    desc: "Body Tailored Self Design Notch Collar Suit Self Design Men Suit",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh2.jpg",
    },
    {
    id: "c",
    name: "Men Casual Shirt",
    price: 399,
    desc: "Men Regular Fit Color Block Casual Vacation lightweight Shirt | Size Ⓜ L S|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh3.png",
    },
    {
    id: "d",
    name: "T-Style Shirt",
    price: 1449,
    desc: "Men's Regular Fit Casual Vacation lightweight Shirt and Free Style Modern| Size S Ⓜ L XXL XXXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh4.jpg",
    },
    
     
    {
    id: "e",
    name: "Men's Cotton Slim Fit",
    price: 349,
    desc: "Men's Solid Premium Slim Fit shirt | Size Ⓜ L |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh5.jpg",
    },
    {
    id: "f",
    name: "Roadster Men",
    price: 699,
    desc: "White Green & Maroon Striped shirt by Eva | Size Ⓜ L |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh6.jpg",
    },
    {
    id: "g",
    name: "Netplay",
    price: 999,
    desc: "City Shirts with Insert Pockets | Size Ⓜ L S XL XXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh7.jpg",
    },
    {
    id: "h",
    name: "Cargo",
    price: 799,
    desc: "Twist Men's Solid Medium Size Shirts| Size Ⓜ L XL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sh8.jpg",
    },
    {
    id: "i",
    name: "El Cielo",
    price: 300,
    desc: "Slim Fit Blue Polycotton Sweatshirt| Size S Ⓜ L XXL| Limited Offer for First Buyer",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee1.png",
    },
    {
    id: "j",
    name: "YB DNMX",
    price: 579,
    desc: "Mid-Rise ZEEL Solid Men Raincoat| Size S Ⓜ L XXL| Limitted Offer for First Buyer",
    
     
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee10.jpg",
    },
    {
    id: "l",
    name: "HIGHLANDER",
    price: 1899,
    desc: "Men Black Tapered Fit Ankle Length Chinos Jacket| Size S Ⓜ |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee12.jpg",
    },
    {
    id: "m",
    name: "JUNEBERRY",
    price: 989,
    desc: "Black Cotton Regular Fit men's T-Shirt | Size S Ⓜ L XXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee2.jpg",
    },
    {
    id: "n",
    name: "WeeJack",
    price: 799,
    desc: "Cotton Regular Fit men's Stylish Jacket | Size S Ⓜ L XXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee3.jpg",
    },
    {
    id: "o",
    name: "Tee-Shirt",
    price: 999,
    desc: "white Polycotton Regular Fit men's T-Shirt | Size S Ⓜ L XXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee4.jpg",
    },
    {
    id: "p",
    name: "Tee-Shirt",
    price: 559,
    desc: "Red Cotton Regular Fit men's T-Shirt | Size S Ⓜ L XXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee5.jpg",
    },
    {
    id: "q",
    name: "Woofer",
    price: 499,
    desc: "Green Cotton Regular Fit men's T-Shirt | Size S Ⓜ L XXL|",
    
     
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee6.png",
    },
    {
    id: "r",
    name: "V T-shirt",
    price: 399,
    desc: "Dual Color Pattern Cotton Regular Fit men's T-Shirt | Size S Ⓜ L XXL| Limited Offer",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee7.png",
    },
    {
    id: "s",
    name: "Classic Men",
    price: 699,
    desc: "Green Light Cotton Regular Fit men's T-Shirt | Size S Ⓜ L XXL| Limited Offer",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee8.png",
    },
    {
    id: "t",
    name: "Black Solo",
    price: 300,
    desc: "Black Nylon Regular Fit men's T-Shirt | Size S Ⓜ L XXL|",
    img: "",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/tee9.jpg",
    },
    {
    id: "u",
    name: "Nice OUt",
    price: 100,
    desc: "Blue PolyCotton Regular Fit men's Stylish Pant | Size S Ⓜ L XXL| Limited Offer",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/pa1.png",
    },
    {
    id: "v",
    name: "Casualize",
    price: 769,
    desc: "Casual Cool Pants | Size S Ⓜ L|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/pa2.png",
    },
    {

     
    id: "w",
    name: "HugoMag",
    price: 899,
    desc: "Casual Cool Pants | Size L Ⓜ|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/pa3.png",
    },
    {
    id: "x",
    name: "Laze Shorts",
    price: 399,
    desc: "Men's Blue casual Shorts | Size S |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/ms1.png",
    },
    {
    id: "y",
    name: "Laze Shorts Jag",
    price: 499,
    desc: "Men's Black casual shorts | Size S Ⓜ L |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/ms2.png",
    },
    {
    id: "z",
    name: "Laze Shorts",
    price: 399,
    desc: "Men's Blue Casual Shorts | Size Ⓜ |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/ms3.png",
    },
    {
    id: "aa",
    name: "Workee",
    price: 399,
    desc: "White Caual Party shorts | Size S L |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/ms4.png",
    },
    {
    id: "cc",
    name: "Siril",
    price: 1499,
    desc: "Embellished Daily Wear Cotton Silk Saree (Blue)",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sr2.jpg",
    },
    {
         
    id: "dd",
    name: "3DBuddy Fashion",
    price: 1899,
    desc: "Solid/Plain Daily Wear Lycra Blend Saree",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sr3.jpg",
    },
    {
    id: "ee",
    name: "OK Kush Trendz",
    price: 1699,
    desc: "Solid/Plain Chanderi Cotton Blend Saree (Red)",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sr4.jpg",
    },
    //Next Products
    {
    id: "ff",
    name: "OK Kush Trendz",
    price: 1499,
    desc: "Solid/Plain Chanderi Cotton Blend Saree (Purple)",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/sr5.jpg",
    },
    {
    id: "hh",
    name: "SumerTex",
    price: 799,
    desc: "Women Fit and Flare Home Dress| Size S Ⓜ L XXL |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/mo1.png",
    },
    {
    id: "ii",
    name: "Mezzz",
    price: 999,
    desc: "Women Fit and Flare Black Dress| Size S Ⓜ L XXL |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/mo2.png",
    },
    {
    id: "jj",
    name: "Yo Shorts",
    price: 899,
    desc: "Women's Free Style Cotton Shorts",
    
     
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/mo3.jpg",
    },
    {
    id: "nn",
    name: "Weesa Modern",
    price: 749,
    desc: "Modern Free Style Pant| Size S L |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/mo8.jpg",
    },
    {
    id: "pp",
    name: "TASWE",
    price: 999,
    desc: "Gray Regular fit T-shirt for Woman",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wtee1.jpg",
    },
    {
    id: "qq",
    name: "FEE BEE",
    price: 699,
    desc: "Rich look Casual T-shirt for women's",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wtee2.jpg",
    },
    {
    id: "rr",
    name: "HOOd",
    price: 449,
    desc: "Women's Casual Hoodie| Size Ⓜ |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wtee3.jpg",
    },
    {
    id: "ss",
    name: "Labo",
    price: 699,
    desc: "Women's Casual T-shirt| Size Ⓜ L |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wtee4.jpg",
    },
    {
    id: "tt",
    name: "Fe-Hale",
    price: 999,
    desc: "Women's Green Casual Cotton T-shirt| Size Ⓜ |",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wtee5.jpg",
    },
    {
    id: "vv",
    name: "Purp Top",
    price: 899,
    desc: "Women's Casual Modern Top| Size S Ⓜ L XXL|",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wtee7.jpg",
    },
    {
    id: "ww",
    name: "Fastrack Carson",
    price: 899,
    desc: "Arrow Blk Arrow Boys Mens Wrist Watch For Boys Analog Watch",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wa1.jpg",
    },
    {
    id: "xx",
    name: "Rolex Zen",
    price: 899,
    desc: "Arrow zds Arrow Boys Mens Wrist Watch For Boys Analog Watch",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wa2.jpg",
    },
    {
    id: "zz",
    name: "Fastrack zx",
    price: 1399,
    desc: "AM02AME stainless steel watch",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wa4.jpg",
    },
    {
    id: "aaa",
    name: "Sonata",
    price: 1099,
    desc: "BT7118 Dial Quartz Mechanism Sports Water Resistant Watch - For Men",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wa5.jpg",
    },
    {
    id: "bbb",
    name: "Timex xxx",
    price: 999,
    
     
    desc: "ER98J00 stainless Steel watch Mens Wrist Watch For Boys Analog Watch",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wa6.jpg",
    },
    {
    id: "ccc",
    name: "Titan Stone",
    price: 999,
    desc: "LS76556GH Mens Wrist Watch For Boys Analog Watch",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/wa7.jpg",
    },
    {
    id: "eee",
    name: " Cowboy BIPTO",
    price: 399,
    desc: "Cowboy Style JEAN hat for Men",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/cp1.jpg",
    },
    {
    id: "fff",
    name: "Samantha Kiss",
    price: 299,
    desc: "Kids Play hat",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/cp2.jpg",
    },
    {
    id: "ggg",
    name: "Winter Huntz",
    price: 399,
    desc: "Men/Women Hot for Winter",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/cp3.jpg",
    },
    {
    id: "hhh",
    name: "Benz CasualllY",
    price: 399,
    desc: "Men/Women Hot for Winter",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/cp4.jpg",
    },
    {
    id: "iii",
    name: "Chevitt",
     
    price: 899,
    desc: "Stylish Comfortable Lightweight, Breathable Walking Shoes For Men",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoe1.jpg",
    },
    {
    id: "jjj",
    name: "Nobellite",
    price: 999,
    desc: "Casual Shoe for Men and Women",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoe2.jpg",
    },
    {
    id: "kkk",
    name: "Sneak",
    price: 799,
    desc: "White Sneaker For Men and Women",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoe3.jpg",
    },
    {
    id: "lll",
    name: "LetBoo",
    price: 1289,
    desc: "Maroon Color Rough Boot for Men",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoe4.jpg",
    },
    {
    id: "mmm",
    name: "Adidass",
    price: 1299,
    desc: "White New Running and Casual Shoe for Men and Women",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoe5.jpg",
    },
    {
    id: "nnn",
    name: "Shortiee",
    price: 1399,
    desc: "Sport Shoe For Cricket, Hockey Men and Women",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoe6.jpg",
    },
    {
    id: "ooo",
     
    name: "LetBOO",
    price: 1199,
    desc: "Rough and Tough trek Shoes for women ",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoes7.jpg",
    },
    {
    id: "ppp",
    name: "LetBOO",
    price: 1299,
    desc: "Rough and Tough Trek Shoes for Men",
    img: "https://eva-fashion-imagebucket.s3.jp-tok.cloud-object-storage.appdomain.cloud/shoes8.jpg",
    },
    ];